language: python
python:
  - "3.6"

install:
  - python setup.py install

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - pip install coveralls

script:
  - coverage run --source weaveserver setup.py test

after_success:
  - coveralls
